version: '3'

services:
  reverseproxy:
    build:
      context: ./nginx
    ports: 
      - 8080:8080
    restart: always
  
  api:
    depends_on: 
      - reverseproxy
    build: 
      context: ./backend/api
    restart: always
  
  auth:
    depends_on: 
      - reverseproxy
    build:
      context: ./backend/auth
    env_file: 
      - ./backend/auth/spotify.env
    restart: always
  
  web:
    depends_on: 
      - reverseproxy
    build:
      context: ./web
    volumes: 
      - ./node_modules
    restart: always