version: '3'

services:
  api:
    build: 
      context: ./backend/api
    ports:
      - "5050:5050"
  auth:
    build:
      context: ./backend/auth
    ports: 
      - "5000:5000"
  web:
    build: 
      context: ./web
    ports: 
      - "3000:3000"
  app:
    build:
      context: ./
    ports:
      - "8000:80"